parameters:
    acme_temporary.form.handler.order.class:     Acme\Bundle\TemporaryBundle\Form\Handler\OrderHandler
    acme_temporary.form.type.order.class:        Acme\Bundle\TemporaryBundle\Form\Type\OrderType
    acme_temporary.form.type.order_item.class:        Acme\Bundle\TemporaryBundle\Form\Type\OrderItemType
services:
    acme_temporary.form.handler.order:
        class: %acme_temporary.form.handler.order.class%
        scope: request
        arguments:
            - @acme_temporary.form.order
            - @request
            - @doctrine.orm.entity_manager

    acme_temporary.form.order:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["acme_temporary_order_form", "acme_bundle_temporary_order"]

    acme_temporary.form.type.order:
        class: %acme_temporary.form.type.order.class%
        tags:
            - { name: form.type, alias: acme_bundle_temporary_order }

    acme_temporary.form.type.order_item:
        class: %acme_temporary.form.type.order_item.class%
        tags:
            - { name: form.type, alias: acme_bundle_temporary_orderitem }
