Acme\Bundle\TemporaryBundle\Entity\Order:
    properties:
        label:
            - NotBlank: ~
        items:
            - Count: { min: 1 }

Acme\Bundle\TemporaryBundle\Entity\OrderItem:
    properties:
        qty:
            - Range: { min: 0 }
            - NotBlank: ~
        product:
            - NotBlank: ~
